sudo: required
services:
  - docker

before_install:
  - docker build -t kwlooi/sample-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kwlooi/sample-react-test npm test -- --coverage

after_success:
  - docker build -t kwlooi/multi-docker-react-client ./client
  - docker build -t kwlooi/multi-docker-react-nginx ./nginx
  - docker build -t kwlooi/multi-docker-react-server ./server
  - docker build -t kwlooi/multi-docker-react-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push kwlooi/multi-docker-react-client
  - docker push kwlooi/multi-docker-react-nginx
  - docker push kwlooi/multi-docker-react-server
  - docker push kwlooi/multi-docker-react-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "Multi-Docker React"
  env: "MultiDockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-716953936909"
  bucket_path: "Multi-Docker React"
  on:
    branch: master
  access_key_id: "$aws_access_key"
  secret_access_key:
    secure: "$aws_secret_key"