sudo: required
services:
  - docker

before_install:
  - docker build -t kwlooi/sample-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kwlooi/sample-react-test npm test -- --coverage

after_success:
  - docker build -t kwlooi/multi-docker-react-client ./client
  - docker build -t kwlooi/multi-docker-react-nginx ./nginx
  - docker build -t kwlooi/multi-docker-react-server ./server
  - docker build -t kwlooi/multi-docker-react-worker ./worker

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker-react"
#   env: "docker-react-env"
#   bucket_name: "elasticbeanstalk-us-east-1-716953936909"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: "$aws_access_key"
#   secret_access_key:
#     secure: "$aws_secret_key"